### ISSUE TITLE
How to use this in a nuxt application?

### ISSUE THREAD

**Issue by kavin404** [palerdot/vue-speedometer#1]
I get this error 
![stack error](https://user-images.githubusercontent.com/26364290/67159710-1f5e5380-f366-11e9-8eb5-191266cb6aeb.PNG)

**Comment by palerdot** [comment]
I think [this link](https://github.com/vuejs/vue-cli/issues/1875#issuecomment-408739414) might of some help to you ... basically you may have to turn on `runTimeCompiler` by creating a file `vue.config.js` with 
```
module.exports = {
  runtimeCompiler: true
}
```

Please reopen if you still face this issue ...
