### ISSUE TITLE
How to make it work without a build step

### ISSUE THREAD

**Issue by martynwheeler** [palerdot/vue-speedometer#12]
Hi,

I was wondering how I could use this without a build step.  I downloaded it from npm and tried it in my app that loads components using httpVueLoader but it didn't work due to the require statements in the dist library.  Any ideas please?

Thanks
Martyn

**Comment by palerdot** [comment]
As far as I see, it is not possible to make it work without a build step. This library is not a single self contained `vue` file, and thus cannot work with [http-vue-loader](https://github.com/FranckFreiburger/http-vue-loader).

I will glad to revisit this issue if someone thinks it is possible to make this work without a build step, but right now I think it is not possible.
