### ISSUE TITLE
Vulnerability in D3 library

### ISSUE THREAD

**Issue by ibustosca** [palerdot/vue-speedometer#59]
Hi,

Currently, there is a vulnerability associated with D3 library:

https://github.com/advisories/GHSA-36jr-mh4h-2g58

This vulnerability is resolved in the 3.1.0 version. However, vue-speedometer still continues working with the 1.x.x version.

The following message appears in my console:

```
vue-speedometer  *
    Depends on vulnerable versions of d3
    node_modules/vue-speedometer
```

Do you have any solution for this?

Thank you so much!

**Comment by palerdot** [comment]
PRs welcome. Unfortunately, currently I don't have time to reliably look into this issue with a fixed deadline. Maybe bump up the version here - https://github.com/palerdot/vue-speedometer/blob/master/package.json#L52, and see if it solves your problem and make a PR to this repo. Mostly I will be able to merge it if there are no other breaking changes with current d3 major version.

**Comment by palerdot** [comment]
`v3` is published with composition api/SFC (single file component) support. This is the recommended version for `Vue 3` composition api users.

From this version, the package has adopted `d3 micro bundles`.
