### ISSUE TITLE
Quasar v2 framework this.querySelector is not a function

### ISSUE THREAD

**Issue by rizky2341** [palerdot/vue-speedometer#67]
hi i have a problem when using the library with quasar framework v2. when i read closed issue, where i suppose to add this code ?
`module.exports = {
  runtimeCompiler: true,
};
`
much appreciate :)
![image](https://github.com/palerdot/vue-speedometer/assets/35560648/784fd020-6d09-4cc0-b1db-06bf8c510ee5)

**Comment by palerdot** [comment]
`runtimeCompiler: true` is a vue specific config and I'm not sure if it really applies to `Vue 3`. You have to check your quasar framework/vue version documentation. I cannot help you here.

**Comment by rizky2341** [comment]
hi, i found how to make it work, in case there's someone have same issues u need to enable this in your **quasar.config.js**. `extendViteConf(viteConf) {
        viteConf.resolve.alias.vue = "vue/dist/vue.esm-bundler.js";
      },` add this piece of line inside build: {};

**Comment by palerdot** [comment]
Possible solution: https://github.com/vitejs/vite/discussions/4158

**Comment by palerdot** [comment]
`v3` is published with composition api/SFC (single file component) support. This is the recommended version for `Vue 3` composition api users.
