### ISSUE TITLE
Get error after build

### ISSUE THREAD

**Issue by HosseinBabmoradi** [palerdot/vue-speedometer#69]
when i run my project in dev mode the vue-speedometer works fine but in production after build the component doesn`t show , even the empty component like this  `<Speedometer />` and i got this error in console `this.querySelector is not a function` 
what is wrong ?

**Comment by palerdot** [comment]
`runtime build` has to enabled in production. It depends on your project setup. For example, in old `vue-cli` you might have to add something like 
```
// vue.config.js
module.exports = {
  runtimeCompiler: true
}
```

For newer vite based setups check out 
https://github.com/vitejs/vite/discussions/4158

Also, please search issues in the repo as others have pointed out different solutions.
https://github.com/palerdot/vue-speedometer/issues/67

Please note, this is not a library problem and it is a build setup/configuring issue.

**Comment by HosseinBabmoradi** [comment]
your right thanks , it helps
